### ISSUE TITLE
Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by ghost** [konstruktoid/Cassandra_Build#2]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but they are set to be enabled by default:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them?
Thanks!

**Comment by konstruktoid** [comment]
Hi @HCHCHH and thanks!
If you're using this container in an production environment or in a staging/pre prod test environment I would follow the official documentation.

**Comment by ghost** [comment]
Thanks for your response!

The default value for these two parameters are already changed to `False` in the [document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html). And is changed in the code for Cassandra 4.

However, in the latest version of Cassandra (3.11.4), the default value for them are still True. We may disable them manually for now.
Thanks!
